on: push

jobs:
  build: 
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v4

      - name: Build index.html file 
        run: python build.py 

      - name: Upload built files
        uses: actions/upload-pages-artifact@v3
        with: 
          path: out/

  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    permissions: 
      pages: write
      id-token: write
    steps:
      - name: Deploy to Github pages 
        uses: actions/deploy-pages@v4

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Test for public javascript library vulnerabilities 
        uses: lirantal/is-website-vulnerable@main
        with:
          scan-url: "https://pokival.github.io/L13-activity/
"


